# Capstone Notebook 3: Testing Models and evaluation

In this notebook, we will evaluate the various models

In [37]:
import numpy as np
import pandas as pd
from PIL import Image

from keras.models import load_model
from keras.preprocessing import image
from keras.optimizers import Adam

df_test = pd.read_csv('./balanced-one-partition/pneumo_dataset_ITI_rev_clean.tsv' , sep="\t")
y, x, in_channel = 524, 524, 1

In [48]:
from pneumo_data_generator import DataGenerator

#from pneumo_data_generator_test import DataGeneratorTest
data_filter  = df_test['Projection']=='PA'
data_filter &= df_test['Partition']=='te'
df_pneumo_2d_test=df_test[ data_filter ]
data_generator_test = DataGenerator( df_pneumo_2d_test[data_filter ], y, x, in_channel, batch_size=1,shuffle=True)

C:\Users\Ben\anaconda3\envs\tensorflowgpu\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys


In [20]:
df_pneumo_2d_test.shape

(2378, 39)

In [39]:
# CNN model
CNNmodel= load_model('./models/modelCNN-train.hdf5')

C:\Users\Ben\anaconda3\envs\tensorflowgpu\lib\site-packages\keras\engine\saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [49]:
predict_CNN = CNNmodel.predict(data_generator_test,steps = len(data_generator_test),verbose=1,
                               workers=1, use_multiprocessing=False)
#predict = np.argmax(predict, axis=1)

2378/2378 [==============================] - 39s 16ms/step


In [ ]:
#data_generator_test.__getitem__(1)
CNNmodel.predict(x=data_generator_test.__getitem__(1))

In [47]:
predict_CNN

array([[0.20709012, 0.79290986],
       [0.20709012, 0.79290986],
       [0.20709012, 0.79290986],
       ...,
       [0.20709012, 0.79290986],
       [0.20709012, 0.79290986],
       [0.20709012, 0.79290986]], dtype=float32)

In [8]:
# VGG model
vggmodel= load_model('./models/vggmodel-train.hdf5')

In [9]:
predict_vgg = vggmodel.predict_generator(data_generator_test,steps = len(data_generator_test),verbose=1,
                               workers=1, use_multiprocessing=False)


2378/2378 [==============================] - 68s 28ms/step


In [21]:
predict_vgg

array([[0.20379415, 0.7962058 ],
       [0.20379415, 0.7962058 ],
       [0.20379415, 0.7962058 ],
       ...,
       [0.20379418, 0.7962058 ],
       [0.20379418, 0.7962058 ],
       [0.20379412, 0.7962058 ]], dtype=float32)

In [9]:
# resnet model
resnetmodel= load_model('./models/resnetmodel-train.hdf5')

In [11]:
predict_resnet = resnetmodel.predict(data_generator_test,steps = len(data_generator_test),verbose=1)


2378/2378 [==============================] - 94s 39ms/step


In [12]:
predict_resnet

array([[0.19495799, 0.805042  ],
       [0.19495799, 0.805042  ],
       [0.19495799, 0.805042  ],
       ...,
       [0.19495799, 0.805042  ],
       [0.19495799, 0.805042  ],
       [0.19495799, 0.805042  ]], dtype=float32)

In [5]:
#inception model
inceptionmodel= load_model('./models/inceptionmodel-train.hdf5')

C:\Users\Ben\anaconda3\envs\tensorflowgpu\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


In [6]:
predict_inception = inceptionmodel.predict(data_generator_test,steps = len(data_generator_test),verbose=1)


2378/2378 [==============================] - 174s 73ms/step


In [7]:
predict_inception

array([[0.19546415, 0.80453587],
       [0.19546415, 0.80453587],
       [0.19546415, 0.80453587],
       ...,
       [0.19546415, 0.80453587],
       [0.19546415, 0.80453587],
       [0.19546415, 0.80453587]], dtype=float32)